(() => {
 const courses=window.REAL_COURSES||[], key='realEduCartV1', money=n=>n.toLocaleString('ko-KR')+'원';
 const samplePrices=[240000,360000,180000,320000,280000,480000,390000];
 courses.slice(2).forEach((c,i)=>{c.price=samplePrices[i];c.sample=true;});
 let cart=[];
 try { const saved=JSON.parse(localStorage.getItem(key)||'[]'); if(Array.isArray(saved))cart=[...new Set(saved)].filter(id=>courses.some(c=>c.id===id)); } catch{}
 const selected=()=>cart.map(id=>courses.find(c=>c.id===id));
 const total=()=>selected().reduce((s,c)=>s+c.price,0);
 const toast=(message,link=false)=>{document.querySelector('.shop-toast')?.remove();const el=document.createElement('div');el.className='shop-toast';el.setAttribute('role','status');el.textContent=message;if(link){const a=document.createElement('a');a.href='cart.html';a.textContent='장바구니 보기';el.append(a);}document.body.append(el);setTimeout(()=>el.remove(),4500);};
 const count=()=>document.querySelectorAll('.cart-count').forEach(el=>{el.textContent=cart.length;el.closest('a')?.setAttribute('aria-label',`장바구니, 담긴 강좌 ${cart.length}개`);});
 const persist=()=>{try{localStorage.setItem(key,JSON.stringify(cart));return true;}catch{toast('브라우저 저장 공간을 사용할 수 없어요. 저장을 허용한 뒤 다시 시도해 주세요.');return false;}};
 function add(id,checkout){if(!courses.some(c=>c.id===id))return;const previous=[...cart];const exists=cart.includes(id);if(!exists)cart.push(id);if(!persist()){cart=previous;return;}count();if(checkout)location.href='checkout.html';else toast(exists?'이미 장바구니에 담긴 강좌예요.':'장바구니에 강좌를 담았어요.',true);}
 count();
 document.querySelectorAll('.course[href],.event-card[href]').forEach(card=>{const c=courses.find(c=>card.getAttribute('href')===c.id+'.html');if(!c)return;const el=document.createElement('div');el.className='catalog-price';el.innerHTML=`<strong>${money(c.price)}</strong><small>${c.sample?'시안 가격 · 전체 과정':'1인 · 1회'}</small>`;card.append(el);});
 const page=location.pathname.split('/').pop().replace('.html','');const current=courses.find(c=>c.id===page);const booking=document.querySelector('.booking');
 if(current&&booking){const p=document.createElement('div');p.className='shop-price';p.textContent=money(current.price);const old=booking.querySelector('.price');if(old)old.replaceWith(p);else booking.prepend(p);const actions=document.createElement('div');actions.className='shop-actions';actions.innerHTML=`<button class="shop-button" data-buy="${current.id}">수강 신청하기</button><button class="shop-button secondary" data-add="${current.id}">장바구니 담기</button>`;booking.append(actions);const note=document.createElement('p');note.textContent=current.sample?'시안 가격 · 확정 수강료와 개강일은 모집 시 안내합니다.':'결제 화면 미리보기 · 실제 결제와 예약은 진행되지 않습니다.';booking.append(note);booking.querySelectorAll('dt').forEach(dt=>{if(dt.textContent==='개강·수강료')dt.textContent='개강 일정';});}
 document.addEventListener('click',event=>{const b=event.target.closest('[data-add],[data-buy],[data-remove]');if(!b)return;if(b.dataset.add)add(b.dataset.add,false);if(b.dataset.buy)add(b.dataset.buy,true);if(b.dataset.remove){const previous=[...cart];cart=cart.filter(id=>id!==b.dataset.remove);if(!persist()){cart=previous;return;}count();renderCart();toast('장바구니에서 삭제했습니다.');}});
 const items=()=>selected().map(c=>`<article class="cart-item"><img src="${c.image}" alt="" width="110" height="85"><div><h2><a href="${c.id}.html">${c.title}</a></h2><p>${c.format} · 1인 수강</p>${c.sample?'<p>시안 가격</p>':''}</div><div class="item-price">${money(c.price)}${page==='cart'?`<br><button class="remove-item" data-remove="${c.id}" aria-label="${c.title} 삭제">삭제</button>`:''}</div></article>`).join('');
 const summary=()=>`<dl><dt>강좌 ${cart.length}개</dt><dd>${money(total())}</dd></dl><dl><dt>할인</dt><dd>0원</dd></dl><dl class="shop-total"><dt>총 금액</dt><dd>${money(total())}</dd></dl><p class="shop-note">표시 금액은 최종 합계 기준입니다. 일반 강좌는 시안 가격이며 실제 결제는 발생하지 않습니다.</p>`;
 function renderCart(){const root=document.querySelector('#cart-content');if(!root)return;if(!cart.length){root.innerHTML='<div class="shop-panel shop-empty"><div class="success-icon">＋</div><h2>다음 배움을 담아보세요.</h2><p>마음에 드는 강좌의 상세 페이지에서<br>장바구니에 담을 수 있어요.</p><a class="shop-button" href="./#courses">강좌 둘러보기 ↗</a></div>';return;}root.innerHTML=`<div class="shop-grid"><div class="shop-panel">${items()}</div><aside class="shop-panel shop-summary"><h2>수강 신청 내역</h2>${summary()}<a class="shop-button" href="checkout.html">주문·결제 화면으로 →</a><a class="shop-button secondary" href="./#courses">강좌 더 둘러보기</a></aside></div>`;}
 renderCart();
 if(page==='checkout'){const root=document.querySelector('#checkout-items');if(!cart.length){document.querySelector('#checkout-form').hidden=true;document.querySelector('#empty-checkout').hidden=false;}else{root.innerHTML=items();document.querySelector('#checkout-summary').innerHTML=summary();}document.querySelectorAll('[name=payment]').forEach(r=>r.addEventListener('change',()=>{document.querySelector('#payment-note').textContent=r.value==='card'?'카드사 선택 이후의 결제 단계를 미리 봅니다. 카드번호는 입력받지 않습니다.':'계좌이체 주문 단계를 미리 봅니다. 입금 요청이나 실제 계좌 안내는 발생하지 않습니다.';}));document.querySelector('#checkout-form').addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return;const f=e.currentTarget;if(!f.reportValidity())return;const order={id:'PREVIEW-'+Date.now().toString(36).toUpperCase(),ids:cart,total:total(),method:new FormData(f).get('payment')};try{sessionStorage.setItem('realEduPreviewOrder',JSON.stringify(order));}catch{toast('브라우저 저장이 차단되어 미리보기를 진행할 수 없어요.');return;}location.href='order-complete.html';});}
 if(page==='order-complete'){let order;try{order=JSON.parse(sessionStorage.getItem('realEduPreviewOrder'));}catch{}const root=document.querySelector('#order-result');if(order&&Array.isArray(order.ids)&&typeof order.total==='number'){root.querySelector('#order-id').textContent=String(order.id);root.querySelector('#order-total').textContent=money(order.total);root.querySelector('#order-method').textContent=order.method==='card'?'신용·체크카드':'계좌이체';root.querySelector('#order-names').textContent=order.ids.map(id=>courses.find(c=>c.id===id)?.title).filter(Boolean).join(' · ');}else root.innerHTML='<h1>아직 미리 본 주문이 없어요.</h1><a class="shop-button" href="cart.html">장바구니로 이동</a>';}
 document.querySelectorAll('[data-auth-form]').forEach(form=>{form.addEventListener('submit',e=>{e.preventDefault();const message=form.querySelector('.form-message');if(!form.reportValidity())return;const password=form.querySelector('[name=password]'),confirm=form.querySelector('[name=confirm]');if(confirm&&password.value!==confirm.value){confirm.setCustomValidity('비밀번호가 일치하지 않습니다.');confirm.reportValidity();return;}message.textContent=form.dataset.authForm==='signup'?'현재 회원가입을 이용할 수 없습니다. 문의하기를 이용해 주세요.':form.dataset.authForm==='reset'?'현재 비밀번호 재설정을 이용할 수 없습니다. 이메일은 발송되지 않았습니다.':'현재 로그인을 이용할 수 없습니다. 문의하기를 이용해 주세요.';form.querySelectorAll('input[type=password]').forEach(i=>i.value='');});form.querySelector('[name=confirm]')?.addEventListener('input',e=>e.target.setCustomValidity(''));form.querySelector('[name=password]')?.addEventListener('input',()=>form.querySelector('[name=confirm]')?.setCustomValidity(''));});
 window.addEventListener('storage',e=>{if(e.key===key){try{const value=JSON.parse(e.newValue||'[]');cart=Array.isArray(value)?[...new Set(value)].filter(id=>courses.some(c=>c.id===id)):[];}catch{cart=[];}count();renderCart();if(page==='checkout')location.reload();}});
 const footer=document.querySelector('footer');if(footer){const el=document.createElement('div');el.className='legal-footer';el.innerHTML='<nav class="legal-links" aria-label="정책 및 이용 안내"><a href="privacy.html">개인정보처리방침</a><a href="terms.html">이용약관</a><a href="refund.html">취소·환불 안내</a><a href="mailto:studio.realday@gmail.com">문의하기</a></nav><div>운영 브랜드: REAL-Edu · 리얼데이 (REALDAY)<br>수업 장소: 서울 성동구 아차산로 5길 19, KL빌딩 5층 503호<br>문의: studio.realday@gmail.com<br>사업자등록번호 · 통신판매업 신고번호 · 대표자 등 사업자 상세 정보는 정식 판매 개시 전 게시 예정입니다.</div>';footer.append(el);}
 const inquiry=document.createElement('dialog');inquiry.className='inquiry-modal';inquiry.setAttribute('aria-labelledby','inquiry-title');inquiry.innerHTML=`<button class="inquiry-close" type="button" aria-label="문의 팝업 닫기">×</button><span class="shop-kicker">LET’S MAKE IT REAL</span><h2 id="inquiry-title">어떤 배움을 찾고 있나요?</h2><p class="inquiry-intro">수강 문의부터 팀 워크숍, 새로운 수업 제안까지.</p><form class="inquiry-form"><label>문의 유형<select name="topic"><option>강좌 수강 문의</option><option>기업·팀 워크숍</option><option>새로운 강좌 제안</option><option>기타 문의</option></select></label><label>문의 내용<textarea name="message" rows="5" required maxlength="2000" placeholder="관심 있는 강좌, 희망 일정, 배우고 싶은 내용을 알려 주세요."></textarea></label><p class="inquiry-help">버튼을 누르면 작성한 내용으로 메일 앱이 열립니다.<br>메일 앱에서 직접 전송해 주세요. 입력 내용은 사이트에 저장되지 않습니다.</p><button type="submit" class="shop-button">이메일로 문의 보내기 ↗</button><p class="inquiry-address">메일 앱이 없다면 <span>studio.realday@gmail.com</span><button type="button" class="copy-email">주소 복사</button></p><p class="form-message" role="status"></p></form>`;document.body.append(inquiry);
 let inquiryTrigger=null;const closeInquiry=()=>inquiry.close();inquiry.querySelector('.inquiry-close').addEventListener('click',closeInquiry);inquiry.addEventListener('click',e=>{if(e.target===inquiry){const r=inquiry.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeInquiry();}});inquiry.addEventListener('close',()=>{document.body.classList.remove('inquiry-open');inquiryTrigger?.focus();});
 document.addEventListener('click',e=>{const link=e.target.closest('a[href^="mailto:studio.realday@gmail.com"]');if(!link)return;e.preventDefault();inquiryTrigger=link;inquiry.showModal();document.body.classList.add('inquiry-open');});
 inquiry.querySelector('form').addEventListener('submit',e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const data=new FormData(e.currentTarget);location.href='mailto:studio.realday@gmail.com?subject='+encodeURIComponent('[REAL-Edu] '+data.get('topic'))+'&body='+encodeURIComponent(data.get('message'));inquiry.querySelector('.form-message').textContent='메일 앱에서 전송을 완료해 주세요. 앱이 열리지 않으면 아래 주소를 복사해 이용할 수 있어요.';});
 inquiry.querySelector('.copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('studio.realday@gmail.com');inquiry.querySelector('.form-message').textContent='이메일 주소를 복사했어요.';}catch{inquiry.querySelector('.form-message').textContent='studio.realday@gmail.com 주소를 직접 선택해 복사해 주세요.';}});
})();
